//! Built-in provider catalog, generated from the models.dev registry
//! (the same catalog OpenCode uses). Entries are OpenAI-compatible
//! upstreams: (provider id, display name, base URL).

pub const BUNDLED_PROVIDERS: &[(&str, &str, &str)] = &[
    ("302ai", "302.AI", "https://api.302.ai/v1"),
    ("abacus", "Abacus", "https://routellm.abacus.ai/v1"),
    (
        "abliteration-ai",
        "abliteration.ai",
        "https://api.abliteration.ai/v1",
    ),
    ("ai-router", "AI-ROUTER", "https://api.ai-router.dev/v1"),
    ("aiand", "ai&", "https://api.aiand.com/v1"),
    ("aki-io", "AKI.IO", "https://aki.io/v1"),
    (
        "alibaba",
        "Alibaba",
        "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    ),
    (
        "alibaba-cn",
        "Alibaba (China)",
        "https://dashscope.aliyuncs.com/compatible-mode/v1",
    ),
    (
        "alibaba-coding-plan",
        "Alibaba Coding Plan",
        "https://coding-intl.dashscope.aliyuncs.com/v1",
    ),
    (
        "alibaba-coding-plan-cn",
        "Alibaba Coding Plan (China)",
        "https://coding.dashscope.aliyuncs.com/v1",
    ),
    (
        "alibaba-token-plan",
        "Alibaba Token Plan",
        "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    ),
    (
        "alibaba-token-plan-cn",
        "Alibaba Token Plan (China)",
        "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    ),
    ("ambient", "Ambient", "https://api.ambient.xyz/v1"),
    ("anyapi", "AnyAPI", "https://api.anyapi.ai/v1"),
    ("auriko", "Auriko", "https://api.auriko.ai/v1"),
    ("bailing", "Bailing", "https://api.tbox.cn/api/llm/v1"),
    ("baseten", "Baseten", "https://inference.baseten.co/v1"),
    ("berget", "Berget.AI", "https://api.berget.ai/v1"),
    (
        "blueclaw",
        "Blue Claw",
        "https://openai.blueclaw.network/v1",
    ),
    ("cerebras", "Cerebras", "https://api.cerebras.ai/v1"),
    ("chutes", "Chutes", "https://llm.chutes.ai/v1"),
    (
        "clarifai",
        "Clarifai",
        "https://api.clarifai.com/v2/ext/openai/v1",
    ),
    ("claudinio", "Claudinio", "https://api.claudin.io/v1"),
    ("cline-pass", "ClinePass", "https://api.cline.bot/api/v1"),
    (
        "cloudferro-sherlock",
        "CloudFerro Sherlock",
        "https://api-sherlock.cloudferro.com/openai/v1",
    ),
    (
        "cohere",
        "Cohere",
        "https://api.cohere.com/compatibility/v1",
    ),
    (
        "coralbricks",
        "CoralBricks",
        "https://inference.coralbricks.ai/v1",
    ),
    ("cortecs", "Cortecs", "https://api.cortecs.ai/v1"),
    ("crof", "CrofAI", "https://crof.ai/v1"),
    ("crossmodel", "CrossModel", "https://api.crossmodel.ai/v1"),
    (
        "crusoe",
        "Crusoe",
        "https://api.inference.crusoecloud.com/v1",
    ),
    ("daoxe", "DaoXE", "https://daoxe.com/v1"),
    (
        "deepinfra",
        "DeepInfra",
        "https://api.deepinfra.com/v1/openai",
    ),
    (
        "digitalocean",
        "DigitalOcean",
        "https://inference.do-ai.run/v1",
    ),
    ("dinference", "DInference", "https://api.dinference.com/v1"),
    ("drun", "D.Run (China)", "https://chat.d.run/v1"),
    ("ebcloud", "EBCloud", "https://maas-api.ebcloud.com/v1"),
    ("edenai", "Eden AI", "https://api.edenai.run/v3"),
    (
        "empiriolabs",
        "EmpirioLabs AI",
        "https://api.empiriolabs.ai/v1",
    ),
    ("evroc", "evroc", "https://models.think.evroc.com/v1"),
    (
        "fastrouter",
        "FastRouter",
        "https://go.fastrouter.ai/api/v1",
    ),
    (
        "fireworks-ai",
        "Fireworks AI",
        "https://api.fireworks.ai/inference/v1",
    ),
    (
        "friendli",
        "Friendli",
        "https://api.friendli.ai/serverless/v1",
    ),
    ("frogbot", "FrogBot", "https://app.frogbot.ai/api/v1"),
    ("gmicloud", "GMI Cloud", "https://api.gmi-serving.com/v1"),
    ("greenpt", "GreenPT", "https://api.greenpt.ai/v1"),
    ("helicone", "Helicone", "https://ai-gateway.helicone.ai/v1"),
    ("hetzner", "Hetzner", "https://inference.hetzner.com/api/v1"),
    ("hpc-ai", "HPC-AI", "https://api.hpc-ai.com/inference/v1"),
    (
        "huggingface",
        "Hugging Face",
        "https://router.huggingface.co/v1",
    ),
    ("hyper", "Charm Hyper", "https://hyper.charm.land/v1"),
    ("iflowcn", "iFlow", "https://apis.iflow.cn/v1"),
    ("impossibl", "Impossibl", "https://api.impossibl.com/v1"),
    ("inception", "Inception", "https://api.inceptionlabs.ai/v1"),
    ("inceptron", "Inceptron", "https://api.inceptron.io/v1"),
    ("inference", "Inference", "https://inference.net/v1"),
    ("inferx", "InferX", "https://model.inferx.net/endpoints/v1"),
    (
        "io-net",
        "IO.NET",
        "https://api.intelligence.io.solutions/api/v1",
    ),
    ("jiekou", "Jiekou.AI", "https://api.jiekou.ai/openai"),
    ("kenari", "Kenari", "https://kenari.id/v1"),
    ("kilo", "Kilo Gateway", "https://api.kilo.ai/api/gateway"),
    (
        "kuae-cloud-coding-plan",
        "KUAE Cloud Coding Plan",
        "https://coding-plan-endpoint.kuaecloud.net/v1",
    ),
    ("lilac", "Lilac", "https://api.getlilac.com/v1"),
    ("llama", "Llama", "https://api.llama.com/compat/v1"),
    ("llmgateway", "LLM Gateway", "https://api.llmgateway.io/v1"),
    ("llmtr", "LLMTR", "https://llmtr.com/v1"),
    ("longcat", "LongCat", "https://api.longcat.chat/openai"),
    ("lucidquery", "LucidQuery", "https://api.lucidquery.com/v1"),
    ("meganova", "Meganova", "https://api.meganova.ai/v1"),
    ("meta", "Meta", "https://api.meta.ai/v1"),
    ("mistral", "Mistral", "https://api.mistral.ai/v1"),
    ("mixlayer", "Mixlayer", "https://models.mixlayer.ai/v1"),
    ("moark", "Moark", "https://moark.com/v1"),
    (
        "modal",
        "Modal",
        "https://inference.us-west.modal.direct/v1",
    ),
    (
        "model-oracle-ai",
        "Model Oracle AI",
        "https://api.modeloracle.com/api/v1",
    ),
    ("modelis", "Modelis", "https://modelishub.com/v1"),
    (
        "modelscope",
        "ModelScope",
        "https://api-inference.modelscope.cn/v1",
    ),
    ("moonshotai", "Moonshot AI", "https://api.moonshot.ai/v1"),
    (
        "moonshotai-cn",
        "Moonshot AI (China)",
        "https://api.moonshot.cn/v1",
    ),
    ("morph", "Morph", "https://api.morphllm.com/v1"),
    ("nano-gpt", "NanoGPT", "https://nano-gpt.com/api/v1"),
    ("nearai", "NEAR AI Cloud", "https://cloud-api.near.ai/v1"),
    (
        "nebius",
        "Nebius Token Factory",
        "https://api.tokenfactory.nebius.com/v1",
    ),
    ("neuralwatt", "Neuralwatt", "https://api.neuralwatt.com/v1"),
    ("nova", "Nova", "https://api.nova.amazon.com/v1"),
    ("novita-ai", "NovitaAI", "https://api.novita.ai/openai"),
    ("ofox", "Ofox", "https://api.ofox.ai/v1"),
    ("ollama-cloud", "Ollama Cloud", "https://ollama.com/v1"),
    ("opencode", "OpenCode Zen", "https://opencode.ai/zen/v1"),
    (
        "opencode-go",
        "OpenCode Go",
        "https://opencode.ai/zen/go/v1",
    ),
    ("orcarouter", "OrcaRouter", "https://api.orcarouter.ai/v1"),
    (
        "ovhcloud",
        "OVHcloud AI Endpoints",
        "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    ),
    ("perplexity", "Perplexity", "https://api.perplexity.ai"),
    (
        "perplexity-agent",
        "Perplexity Agent",
        "https://api.perplexity.ai/v1",
    ),
    ("pioneer", "Pioneer", "https://api.pioneer.ai/v1"),
    ("poe", "Poe", "https://api.poe.com/v1"),
    ("poolside", "Poolside", "https://inference.poolside.ai/v1"),
    ("qihang-ai", "QiHang", "https://api.qhaigc.net/v1"),
    ("qiniu-ai", "Qiniu", "https://api.qnaigc.com/v1"),
    ("regolo-ai", "Regolo AI", "https://api.regolo.ai/v1"),
    ("requesty", "Requesty", "https://router.requesty.ai/v1"),
    ("routing-run", "routing.run", "https://api.routing.run/v1"),
    ("sakana", "Sakana AI", "https://api.sakana.ai/v1"),
    ("sarvam", "Sarvam AI", "https://api.sarvam.ai/v1"),
    ("scaleway", "Scaleway", "https://api.scaleway.ai/v1"),
    (
        "scnet-token-plan",
        "SCNet Token Plan",
        "https://api.scnet.cn/api/llm/v1",
    ),
    ("scx", "SCX.ai", "https://api.scx.ai/v1"),
    (
        "siliconflow",
        "SiliconFlow",
        "https://api.siliconflow.com/v1",
    ),
    (
        "siliconflow-cn",
        "SiliconFlow (China)",
        "https://api.siliconflow.cn/v1",
    ),
    (
        "stackit",
        "STACKIT",
        "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
    ),
    ("stepfun", "StepFun (China)", "https://api.stepfun.com/v1"),
    (
        "stepfun-ai",
        "StepFun (Global)",
        "https://api.stepfun.ai/v1",
    ),
    (
        "stepfun-ai-step-plan",
        "StepFun Step Plan (Global)",
        "https://api.stepfun.ai/step_plan/v1",
    ),
    (
        "stepfun-step-plan",
        "StepFun Step Plan (China)",
        "https://api.stepfun.com/step_plan/v1",
    ),
    ("submodel", "submodel", "https://llm.submodel.ai/v1"),
    (
        "synthetic",
        "Synthetic",
        "https://api.synthetic.new/openai/v1",
    ),
    (
        "tencent-coding-plan",
        "Tencent Coding Plan (China)",
        "https://api.lkeap.cloud.tencent.com/coding/v3",
    ),
    (
        "tencent-token-plan",
        "Tencent Token Plan",
        "https://api.lkeap.cloud.tencent.com/plan/v3",
    ),
    (
        "tencent-tokenhub",
        "Tencent TokenHub",
        "https://tokenhub.tencentmaas.com/v1",
    ),
    ("tensorx", "TensorX", "https://api.tensorx.ai/v1"),
    ("the-grid-ai", "The Grid AI", "https://api.thegrid.ai/v1"),
    ("tinfoil", "Tinfoil", "https://inference.tinfoil.sh/v1"),
    ("togetherai", "Together AI", "https://api.together.xyz/v1"),
    (
        "trustedrouter",
        "TrustedRouter",
        "https://api.trustedrouter.com/v1",
    ),
    ("umans-ai", "Umans AI", "https://api.code.umans.ai/v1"),
    (
        "umans-ai-coding-plan",
        "Umans AI Coding Plan",
        "https://api.code.umans.ai/v1",
    ),
    ("unorouter", "UnoRouter", "https://api.unorouter.com/v1"),
    ("upstage", "Upstage", "https://api.upstage.ai/v1/solar"),
    ("venice", "Venice AI", "https://api.venice.ai/api/v1"),
    (
        "vercel",
        "Vercel AI Gateway",
        "https://ai-gateway.vercel.sh/v1",
    ),
    ("vivgrid", "Vivgrid", "https://api.vivgrid.com/v1"),
    ("vultr", "Vultr", "https://api.vultrinference.com/v1"),
    ("wafer.ai", "Wafer", "https://pass.wafer.ai/v1"),
    (
        "wandb",
        "Weights & Biases",
        "https://api.inference.wandb.ai/v1",
    ),
    ("xai", "xAI", "https://api.x.ai/v1"),
    ("xiaomi", "Xiaomi", "https://api.xiaomimimo.com/v1"),
    (
        "xiaomi-token-plan-ams",
        "Xiaomi Token Plan (Europe)",
        "https://token-plan-ams.xiaomimimo.com/v1",
    ),
    (
        "xiaomi-token-plan-cn",
        "Xiaomi Token Plan (China)",
        "https://token-plan-cn.xiaomimimo.com/v1",
    ),
    (
        "xiaomi-token-plan-sgp",
        "Xiaomi Token Plan (Singapore)",
        "https://token-plan-sgp.xiaomimimo.com/v1",
    ),
    ("xpersona", "Xpersona", "https://www.xpersona.co/v1"),
    ("zai", "Z.AI", "https://api.z.ai/api/paas/v4"),
    (
        "zai-coding-plan",
        "Z.AI Coding Plan",
        "https://api.z.ai/api/coding/paas/v4",
    ),
    ("zeldoc", "Zeldoc", "https://api.zeldoc.ai/v1"),
    ("zenifra", "Zenifra", "https://ai.zenifra.com/v1"),
    ("zenmux", "ZenMux", "https://zenmux.ai/api/v1"),
    (
        "zhipuai",
        "Zhipu AI",
        "https://open.bigmodel.cn/api/paas/v4",
    ),
    (
        "zhipuai-coding-plan",
        "Zhipu AI Coding Plan",
        "https://open.bigmodel.cn/api/coding/paas/v4",
    ),
];
